### ISSUE TITLE
Error Oracle insertando valor null en el campo ACH_VALORPRIMARI"."TERMINI"

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/archium#10]
Revisando los logs de archium vemos que aparece este error de base de datos:

... 115 more
6	Caused by: java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("ARCHIUM"."ACH_VALORPRIMARI"."TERMINI")
7	
8	at com.oracle@18.3.0.0.0//oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
9	at com.oracle@18.3.0.0.0//oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446) 
09:07:33: Antoni Juanico Soler: Caused by: Error : 1400, Position : 85, Sql = insert into ARCHIUM.ACH_VALORPRIMARI (termini, TIPUSVALOR_ID, VALORACIO_ID) values (:1 , :2 , :3 ), OriginalSql = insert into ARCHIUM.ACH_VALORPRIMARI (termini, TIPUSVALOR_ID, VALORACIO_ID) values (?, ?, ?), Error Msg = ORA-01400: cannot insert NULL into ("ARCHIUM"."ACH_VALORPRIMARI"."TERMINI") 

¿Podríais añadir algún control en la pantalla de usuario para evitar que se produzca este error?

**Comment by dsariego-memorandum** [comment]
Según se habló por correo, se opta como solución eliminar la obligatoriedad de este campo. En el commit de ayer se modifica el script de creación para quitarla. Toni Gayá mandó el correo para modificar las bases de datos existentes.
Se considera con esto solucionada la incidencia por nuestra parte

**Comment by tgaya-dgtic** [comment]
Resolta.
