### ISSUE TITLE
Errores de codificación en desplegable DIr3

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/archium#12]
Al desplegar el campo del Dir3 aparecen símbolos en el lugar donde deberían aparecer
acentos.
![image](https://user-images.githubusercontent.com/17315737/100590573-dad91180-32f4-11eb-87e3-468b31536b4a.png)

**Comment by tgaya-dgtic** [comment]
parece que afecta a properties en general, columnas de base de datos...

**Comment by dsariego-memorandum** [comment]
Buenas,

¿En la versión 1.0.0? a mí me aparece correctamente tanto en el dir3 como en otras partes de la aplicación.

![imagen](https://user-images.githubusercontent.com/71632820/107964772-ed84ed80-6fa9-11eb-9b0f-b3a9ddefe33c.png)

**Comment by tgaya-dgtic** [comment]
Esto seguramente es debido a que la subida de datos de esta/s tabla/s a Oracle no la han hecho especificando la codificación correspondiente.
Pediré que la/s vuelvan a subir.

**Comment by dsariego-memorandum** [comment]
Buenas Toni,

Según veo los dir3 se cargan de un fichero que se encuentra en la ruta "archium-ejb/src/main/resources/data/DIR3.csv", el cual a mí se me carga correctamente, tanto desde la aplicación como abriéndolo con el Excel:
![imagen](https://user-images.githubusercontent.com/71632820/108040418-8d3f8b80-703d-11eb-8f17-ea5f3c16123d.png)
Si quieres te paso el archivo  por correo, pero debería ser el mismo que está en el repositorio

**Comment by tgaya-dgtic** [comment]
Le he pedido a Adrian la lista de las tablas que les fallan.
Insisto, para mí es que cuando en Sistemas han hecho la subida de datos a Oracle no han especificado la codificación de los ficheros, y Oracle ha aplicado por defecto una codificación que no coincide con la que tienen los ficheros.

**Comment by tgaya-dgtic** [comment]
David, ese dir3.csv no tiene formato de tabla. Es decir, tiene varias columnas desalineadas.
Podrías, a través de tu propia tabla DIR3, generarme un update_DIR3.sql con los updates necesarios para modificar la tabla DIR3 de la bbdd nuestra con las cadenas de carácteres correctos?

**Comment by tgaya-dgtic** [comment]
Bueno, esta mañana hemos quedado que como es un fichero csv, quizá el problema es que no lo lee con la codificación UTF-8. Y que lo comprobarías.
Si se fuerza que lo lea como UTF-8 y sigue fallando, también podría ser que lo lea como UTF-8 pero lo muestre por pantalla como si fuera ascii.

**Comment by dsariego-memorandum** [comment]
Solucionado, el formato del CSV es ISO_8859_1, por algún motivo en el entorno de PRO no lo decodificaba bien, probé forzándolo a UTF-8 la decodificación y pasaba el mismo problema que se reporta aquí, forzándolo al charset del archivo lo muestra correctamente, espero que con esto se solucione la incidencia en PRO también

**Comment by tgaya-dgtic** [comment]
Pues tienes razón, el formato del fichero no es utf8. Entonces, claro, java lo leía por defecto como utf8 y luego se mostraba mal.

**Comment by tgaya-dgtic** [comment]
Se da por solucionada.
