### ISSUE TITLE
El botón de cerrar sesión está inactivo

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/archium#13]
Cuando se cierra sesión el botón de CERRAR SESIÓN no está operativo, hay que cerrar directamente desde el aspa de la parte superior izquierda.

![image](https://user-images.githubusercontent.com/17315737/100590715-0d830a00-32f5-11eb-868a-297b2f8b30e7.png)

**Comment by tgaya-dgtic** [comment]
Resolta.
