### ISSUE TITLE
Revisar comportamiento campo serie esencial en pantalla Dictamen

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/archium#14]
En la pestaña Dictàmen,  el campo serie esencial aparece por defecto como SI, de manera que lo puedes modificar a NO,
según sea el caso. Entendemos así que se trata de un campo obligatorio. Adrián nos indica que en
Archium este campo es opcional, por lo que no nos cuadra con lo que nosotras visualizamos. ¿Podeis comprobar si efectivamente en Archium es opcional?

![image](https://user-images.githubusercontent.com/17315737/100590857-3acfb800-32f5-11eb-8378-30435ef2292b.png)

**Comment by dsariego-memorandum** [comment]
Buenas,

SERIEESENCIAL es un campo opcional de la tabla de dictámenes, el "problema" está en que la aplicación es un booleano, por lo tanto siempre tendrá valor. 
En base de datos se trata de un número cuyo valor puede ser 1, 0 o null, lo que se traduce en la aplicación como 1 = true, 0 o null = false
De la misma manera, a la hora de crearlo, en la vista siempre tendrá valor, por lo que siempre se guardará algo en ese campo en base de datos. Pero actualmente (no sé si se cambió desde que se abrió esta incidencia) serie esencial aparece como NO por defecto.

Resumiendo:
-La aplicación acepta tener un valor nulo en este campo (introducido por consulta), pero lo traducirá como un false ('No' en la vista)
-En la creación desde la aplicación siempre tendrá un valor, aunque por lo contrario de lo que se dice aquí, el valor por defecto es NO

**Comment by dsariego-memorandum** [comment]
Se cambia el botón booleano por un combobox, en el que se permite no seleccionar opción (valor nulo)

**Comment by tgaya-dgtic** [comment]
Se da por solucionada.
