### ISSUE TITLE
Incluir un buscador en el campo Aplicaciones al dar de alta un nuevo procedimiento

### ISSUE THREAD

**Issue by tgaya-dgtic** [GovernIB/archium#15]
A la hora de crear un nuevo procedimiento, en la pestaña 'Relacions' el desplegable para Aplicaciones debería incluir un buscador para seleccionarla por el nombre de la aplicación.
También sería útil que se mostrasen ordenadas alfabéticamente.

**Comment by dsariego-memorandum** [comment]
Se añade un filtro por contenido en el combobox de aplicaciones, como se hizo con otros campos en otras incidencias.
Además, apliqué un orderBy a la consulta a base de datos para obtener las aplicaciones ordenadas por nombre

**Comment by tgaya-dgtic** [comment]
Se da por solucionada.
