### ISSUE TITLE
Establecer la cardinalidad de los tipos documentales dentro de un procedimiento

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/archium#16]
Interesa poder establecer la cardinalidad de los tipos documentales dentro de un procedimiento.
Hasta ahora únicamente se contemplaba la obligatoriedad (u opcionalidad, según se mire) de los documentos dentro de un procedimiento.
Interesa también poder mantener la cardinalidad de éstos.

Propuesta de solución:
- Añadir columna "MULTIPLE" NUMBER(1,0) en la tabla ACH_TIPUSDOCUMENT_PROCEDIMENT.
- Modificar la aplicación web (alta y modificación de procedimiento) para poder mantener esta columna (igual que el check de obligatorio). Label del nuevo check: "Múltiple"

Se adjunta captura de pantalla.
![imatge](https://user-images.githubusercontent.com/17315737/104298472-4f8e9680-54c4-11eb-97de-c2783011fb83.png)

**Comment by dsariego-memorandum** [comment]
Se añade nuevo campo en la tabla, y su  correspondiente check en la vista. Se envía script por correo para la modificación de las bases de datos ya existentes

**Comment by tgaya-dgtic** [comment]
Falta definir la sentencia exacta que tiene que ejecutar Sistemas para actualizar la bbdd.

**Comment by dsariego-memorandum** [comment]
Se añade en el apartado de scripts una ruta de carpetas donde añadir, por versiones, las modificaciones necesarias en la base de datos

**Comment by tgaya-dgtic** [comment]
Incidencia 16. Error al editar procediment
    Abrir un procedimiento para editarlo.
    Pestaña "Tipus documentals"
    Añadir cualquier tipo documental
    Botón guardar
    Error
    Sólo si antes le doy al botón de "Aceptar" antes de Guardar, parece que guarda. ¿Podría permitir guardar todo sin necesidad del botón "Aceptar"? Tener un botón Aceptar y otro Guardar resulta lioso para el usuario...
    Creemos que este error está desde antes (no se ha introducido arreglando esta incidencia)

**Comment by dsariego-memorandum** [comment]
Este error es por un caso diferente de lo que se trata en esta incidencia. De todas formas se ha revisado y se ha cambiado la lógica del funcionamiento de la operación para poder quitar el botón Aceptar para agregar los tipos documentales

**Comment by tgaya-dgtic** [comment]
Segons la reunió d'avui matí, diuen que està solucionat a la versió 1.0.2
