### ISSUE TITLE
Los campos de tipo fecha no mantienen la hora

### ISSUE THREAD

**Issue by tgaya-dgtic** [GovernIB/archium#18]
Se ha observado que los campos tipo Date no están guardando la hora, sino únicamente el día.
No se ha verificado con todas las tablas, pero parece que es generalizado.
Las columnas inici, modificacio y fi deberían registrar también la hora.

Os paso la relación de tablas afectadas:
ACH_QUADRECLASSIFICACIO MODIFICACIO
ACH_QUADRECLASSIFICACIO INICI
ACH_QUADRETIPUSDOCUMENTAL FI
ACH_QUADRETIPUSDOCUMENTAL MODIFICACIO
ACH_QUADRETIPUSDOCUMENTAL INICI
ACH_CATALEGSERIES FI
ACH_CATALEGSERIES INICI
ACH_APLICACIO_SERIE FI
ACH_APLICACIO_SERIE INICI
ACH_DICTAMEN_TIPUSDOCUMENTAL FI
ACH_DICTAMEN_TIPUSDOCUMENTAL INICI
ACH_LIMITACIO_NORMATIVA_SERIE FI
ACH_LIMITACIO_NORMATIVA_SERIE INICI
ACH_NORMATIVA_SERIEDOCUMENTAL FI
ACH_NORMATIVA_SERIEDOCUMENTAL INICI
ACH_TRANSFERENCIA FI
ACH_TRANSFERENCIA INICI
ACH_VALORACIO FI
ACH_VALORACIO INICI
ACH_PROCEDIMENT MODIFICACIO
ACH_DICTAMEN FI
ACH_DICTAMEN INICI
ACH_FUNCIO FI
ACH_FUNCIO MODIFICACIO
ACH_FUNCIO INICI
ACH_QUADRECLASSIFICACIO FI
ACH_TIPUSDOCUMENTAL FI
ACH_TIPUSDOCUMENTAL MODIFICACIO

**Comment by dsariego-memorandum** [comment]
Buenas,

Esto es debido a que los campos son guardados como DATE, aunque realmente este formato sí guarda la hora, minuto y segundo, puedes ver esto de varias maneras:
Editando de manera visual el campo, podrás ver la hora en cuestión:
![imagen](https://user-images.githubusercontent.com/71632820/107647479-7da9f680-6c7b-11eb-854e-546a62bc739c.png)

También utilizando la función TO_CHAR en la consulta, puedes transformar al formato deseado dicha fecha, por ejemplo:

![imagen](https://user-images.githubusercontent.com/71632820/107648176-4720ab80-6c7c-11eb-91b9-366d84bd611b.png)

He probado a cambiar el tipo de las tablas a TIMESTAMP en vez de DATE, para así previsualizar el formrato completo de la fecha, pero esto provocaba entre otras cosas problemas con la zona horaria en la aplicación, o numerosos calendarios que tiene la aplicación, los cuales habría que modificar su lógica (cuyas soluciones no son del todo sencillas).

Además, en la aplicación ya se está viendo con el formato completo.

Un saludo,

**Comment by tgaya-dgtic** [comment]
Adrian da el Ok para cerrarla.
