### ISSUE TITLE
La creación o modificación de dictamen obliga a introducir plazo.

### ISSUE THREAD

**Issue by tgaya-dgtic** [GovernIB/archium#19]
En la base de datos consta como opcional. A priori parece que también debería ser opcional en la aplicación. No sabemos por qué obliga

**Comment by dsariego-memorandum** [comment]
Esta obligatoriedad se había quitado para la nueva versión de Archium (2.0.0). Cambio realizado en esta versión también (1.0.2).

**Comment by tgaya-dgtic** [comment]
Segons la reunió d'avui matí, diuen que està solucionat a la versió 1.0.2

**Comment by tgaya-dgtic** [comment]
Quan intentes modificar un termini d'un dictamen per a posar-li NULL posa "Dades salvades" però realment no modifica res. Sí que guarda quan modifiques d'un valor no null a un altre valor no null (falta corregir alguna petita condició per tal de transferir les dades modificades a la BD)

**Comment by tgaya-dgtic** [comment]
Ok de n'Adrian.
