### ISSUE TITLE
Error al crear nueva función

### ISSUE THREAD

**Issue by lauramemorandum** [GovernIB/archium#2]
Detectado error en la creación de una nueva función.

Toni Trobat informa de la incidecia detectada por Mateu:

Bon dia Toni
He provat de donar d'alta una funció al quadre de classificació (carregat) i no em deixa ni a pre ni a pro.
![#02_01](https://user-images.githubusercontent.com/12030727/92738819-933d8c00-f37c-11ea-846d-12e9c1e6cc04.jpg)

El error surge cuando seleccionas la función padre
![#02_02](https://user-images.githubusercontent.com/12030727/92738841-98024000-f37c-11ea-8d01-f7f705c051ac.jpg)

Cordialment,
Mateu Ramon i Lidón
Servei d'Arxiu Digital

**Comment by atrobat-dgtic** [comment]
Hemos hecho pruebas y funciona.
