### ISSUE TITLE
Modificación nombre datasource

### ISSUE THREAD

**Issue by lauramemorandum** [GovernIB/archium#3]
De: Antonio Trobat Obrador <departamentals1@dgtic.caib.es> 
Enviado el: viernes, 11 de septiembre de 2020 09:40
Para: laura@memorandum.net
CC: 'Antoni Gayà Gayà' <tgaya@dgtic.caib.es>
Asunto: RE: Error en Archium

Perfecto ahora lo probamos.

Por cierto, podriais modificar una cosa en Archium? Este cambio no és urgente. En el fichero E:\desenvolupament\projectes-interoperabilitat\archium\archium-persistence\src\main\resources\META-INF\persistence.xml donde se configura el nombre del datasource dice:

<jta-data-source>es.caib.archium.ds</jta-data-source>

Podriais modificarlo por:

<jta-data-source>es.caib.archium.db</jta-data-source>

Muchas gracias

Salutacions,
  
Toni Trobat Obrador

**Comment by lauramemorandum** [comment]
Solucionado en este commit: https://mmultimedia.slack.com/archives/D011GAEQZ4G/p1601994376001500

Una vez hagais pull debéis cambiar en la configuración de JBoss el nombre del datasource

<xa-datasource jndi-name="java:/es.caib.archium.**db**" pool-name="es.caib.archium.**db**">
...        
</xa-datasource>

**Comment by atrobat-dgtic** [comment]
Perfecto, cierro la incidencia.
