### ISSUE TITLE
Añadir nuevas opciones de filtros en varias pantallas

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/archium#5]
A continuación enumeramos una serie de mejoras que sa han pedido para implementar nuevos filtros de búsqueda:

- En la pantalla DICTAMEN el campo NORMATIVA APROVACIÓ. Debería tener un buscador para poder localizar la normativa rápida y fácilmente.

- En la pantalla NOU PROCEDIMENT en la pestaña de DATOS BÁSICOS el campo SERIE DOCUMENTAL. Al crear un nuevo procedimiento en la pestaña Datos básicos, el campo Serie documental también debería tener un buscador, pues será necesario parar localizar fácilmente una serie concreta cuando las tengamos todas subidas. Todos los BUSCADORES deberían buscar por palabra.

**Comment by dsariego-memorandum** [comment]
Añadido un filtro que filtra por cualquier cosa que introduzcas en el nombre de la serie, por ejemplo, si pones un ‘5’ te saldrán solo las series que tengan un 5 en el nombre. Lo mismo para la normativa aprovacio en la modal del dictamen.

Damos por solucionada la incidencia con esta ampliación.
