### ISSUE TITLE
Poner por defecto la opción ANYS en los campos temporales de Serie Documental i Dictàmen

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/archium#6]
Los CAMPOS TEMPORALES deberían tener seleccionado por defecto la opción ANYS, para hacer el trabajo más ágil ya que es la opción que se utilizará habitualmente. Esto debería aplicarse en Serie documental y en Dictamen.
![image](https://user-images.githubusercontent.com/17315737/97847847-88560680-1cf0-11eb-919b-ac1d00611d0b.png)

![image](https://user-images.githubusercontent.com/17315737/97847877-92780500-1cf0-11eb-9c3d-cc50df6e0b34.png)

En NUEVO PROCEDIMIENTO en la pestaña DATOS BÁSICOS en el campo TERMINI debería aparecer seleccionada por defecto la opción MESOS.
![image](https://user-images.githubusercontent.com/17315737/97848047-d1a65600-1cf0-11eb-8c96-1536a0550486.png)

**Comment by nassau-t** [comment]
N'Adrian concreta:
Hauria de ser valor per defecte Anys als valors administratiu, fiscal, jurídic i altres, així com el termini del dictamen. I valor per defecte Mesos, als terminis de procediment.

**Comment by tgaya-dgtic** [comment]
N'Adrian concreta:
Hauria de ser valor per defecte Anys als valors administratiu, fiscal, jurídic i altres, així com el termini del dictamen. I valor per defecte Mesos, als terminis de procediment.

**Comment by dsariego-memorandum** [comment]
Se cambia el valor por defecto de los combobox a años en series y dictámenes y a meses en procedimientos

**Comment by tgaya-dgtic** [comment]
REABIERTA:
Al guardar un valor primario sin termini, pasa de Anys a Hores...

**Comment by dsariego-memorandum** [comment]
¿Puedes decirme los pasos para intentar reproducirlo? He intentado:
-Crear una serie con valor secundario, pero sin informar ninguno primario, y da un error de que debe informarse este.
![imagen](https://user-images.githubusercontent.com/71632820/107965713-22457480-6fab-11eb-8c50-d813193a1f09.png)

-Si intento crear la serie sin valor secundario y sin informar plazo en el valor primario, guarda la serie como si no tuviese ninguna valoración

Pero en ninguno de los casos se guarda ningún plazo en horas, ni los combobox cambia a horas.

**Comment by dsariego-memorandum** [comment]
Esto era debido a que al no informarse el plazo, se guardaba un valor nulo, se contempla en el código para que cuando no se informa el plazo, este automáticamente sea 0 y así no pierda la unidad, de la misma manera, si no se informase el plazo (a priori no es posible) pondrá la unidad por defecto para el plazo

**Comment by dsariego-memorandum** [comment]
Se cambia la lógica para permitir que el término sea nulo (conservando la unidad seleccionada)

**Comment by tgaya-dgtic** [comment]
Incidencia 6. No guarda valoración ni al crear ni al editar una serie documental.
Pestaña Valoracio
Marcar un valor primario sin plazo.
Al guardar y volver a mirar la pestaña Valoracio, no se ha guardado el valor primario sin plazo (sigue saliendo desmarcado).
   
Parece que no se está mostrando el mensaje de error de "La valoracio debe estar vacía o debe seleccionarse valor primari y secundari, no solo uno de ellos" sólo sale si se ha especificado plazo, pero si sólo se marca el valor primario no sale.
Si se indica valor primario (sin plazo) y secundario, entonces sí guarda. Falta precisar que salga también el aviso de error al marcar sólo el valor primario sin el plazo.

**Comment by dsariego-memorandum** [comment]
Este error es por un caso diferente del que se trataba en esta incidencia, ya está también revisado y solucionado

**Comment by tgaya-dgtic** [comment]
Diuen que està solucionat a la versió 1.0.2
