### ISSUE TITLE
Problema en el visor de pantalla de proedimiento

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/archium#7]
Cuando queremos modificar un procedimiento creado anteriormente sale la pantalla cortada y con la barra de abajo consigo desplazarla pero siempre queda cortada a izquierda o derecha es imposible poder ver la pantalla entera para trabajar con comodidad.
![image](https://user-images.githubusercontent.com/17315737/97848165-f7cbf600-1cf0-11eb-8a84-fd994658808c.png)
![image](https://user-images.githubusercontent.com/17315737/97848186-fef30400-1cf0-11eb-8926-9aa3ef766279.png)
En cambio cuando lo que hacemos es un nuevo procedimiento (crearlo) la pantalla si se ve entera y se puede trabajar cómodamente.

**Comment by tgaya-dgtic** [comment]
Resuelta.
