### ISSUE TITLE
Problemas scroll en la pantalla de serie documental

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/archium#8]
Nos reportan los usuarios de Archium que  la barra lateral de desplazamiento  mueve la ventana principal del navegador, pero no se desplaza el contenido interior de la aplicación. Esto impide llegar a partes de la pantalla como el botón de guardar. Puede que esto pase en otras pantallas de la aplicación.

![imatge](https://user-images.githubusercontent.com/17315737/97961354-71c4b380-1db3-11eb-89b5-a4c436664192.png)

**Comment by dsariego-memorandum** [comment]
No fui capaz a reproducir ese caso concreto, ya que no me pasa ni haciendo la ventana del explorador más pequeña, de todas formas, he añadido una scrollbar a la modal, espero que con esto se solucione el problema. 
Debido al contenido de la modal, requiere un mínimo de tamaño para poder visualizarse correctamente. Con este cambio creo que podrán trabajar con ella en pantallas de un mínimo de 600px de ancho, que es bastante pequeña, para pantallas más pequeñas habría que hacer otra versión que permita visualizarlo correctamente (al igual que existen, por ejemplo, las versiones para móviles). Esto significaría rehacer la modal desde 0 y tendría una gran complejidad, así que espero que con el cambio añadido sea suficiente

**Comment by tgaya-dgtic** [comment]
Se da por solucionada.
