### ISSUE TITLE
Permitir modificar la función dentro de la pantalla de Serie Documenal

### ISSUE THREAD

**Issue by atrobat-dgtic** [GovernIB/archium#9]
Se debería poder modificar la Función cuando se accede a Modifica Serie documental. Se ha dado el caso en que se ha seleccionado una función errónea y cuando se ha querido modificar la única solución que encontramos para poder hacerlo es eliminando la serie y volviéndola a crear para así seleccionar la función correcta.

También se podría dar el caso, más adelante, de querer cambiar la función de una serie, por los mtivos que sean, por lo que debería poderse hacer sin tener que volver a crear la serie de nuevo.

![imatge](https://user-images.githubusercontent.com/17315737/97961445-a173bb80-1db3-11eb-8ecb-f694622361a5.png)

**Comment by tgaya-dgtic** [comment]
Resuelta en archium-v1.0.1. Pendiente de pasarlo a PRE.
